source ~/.profile

source /usr/share/zsh-antigen/antigen.zsh

export ZSH_THEME=""
antigen use oh-my-zsh

antigen bundle sindresorhus/pure@main
zstyle ':prompt:pure:prompt:success' color green
zstyle ':prompt:pure:prompt:error' color red

antigen bundle git
antigen bundle git-auto-fetch
antigen bundle zsh-users/zsh-completions
antigen bundle pip
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

KEYTIMEOUT=1
bindkey -v
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

autoload -U +X compinit && compinit
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

[[ -x "$(command -v gh)" ]] && eval "$(gh copilot alias -- zsh)"

[[ -x "$(command -v direnv)" ]] && eval "$(direnv hook zsh)"

[[ -x "$(command -v uv)" ]] && eval "$(uv generate-shell-completion zsh)"

export PURE_GIT_PULL=0
export GIT_AUTO_FETCH_INTERVAL=1200

plugins=(
  git-auto-fetch
)
