version: '3'
services:
  v2ray:
    image: ghcr.io/xtls/xray-core:1.8.23-ls
    command:
      - run
      - -config
      - /opt/v2ray/config.json
    restart: always
    volumes:
      - ./v2ray.json:/opt/v2ray/config.json:ro
      - ./run/v2ray/log/:/opt/log/:rw
    ports:
      - "2080:2080"
      - "2081:2081"
