version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:v5.2.1
    command:
      - run
      - -config
      - /opt/v2ray/config.json
    restart: unless-stopped
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./v2ray.json:/opt/v2ray/config.json:ro
      - ./run/v2ray/log/:/opt/log/:rw
    expose:
      - 1310
    networks:
      - default
      - proxy

  namizun:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    network_mode: host
    restart: unless-stopped

networks:
  proxy:
    name: reverse-proxy
    external: true
