services:
  namizun:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - REDIS_SOCKET=/var/run/redis/redis.sock
    network_mode: host
    restart: unless-stopped
    volumes:
      - redis-socket:/var/run/redis/
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - >
        mkdir -p /var/run/redis &&
        chown -R redis /var/run/redis/ &&
        redis-server --port 0 --unixsocket /var/run/redis/redis.sock
    volumes:
      - redis-socket:/var/run/redis/

volumes:
  redis-socket:
